apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: backend-pod-killer
  namespace: resilience
spec:
  action: pod-failure
  mode: fixed
  value: "2"
  duration: "45s"
  selector:
    namespaces:
      - resilience
    labelSelectors:
      app.kubernetes.io/component: backend
