import http from 'k6/http';
import { check, sleep } from 'k6';
import { Counter, Rate, Trend } from 'k6/metrics';

const TASK_API = __ENV.TASK_API || 'http://localhost:8080';

const tasksCreated = new Counter('tasks_created');
const fallbackRate = new Rate('fallback_responses');
const requestDuration = new Trend('request_duration');

export const options = {
  stages: [
    { duration: '30s', target: 50 },
    { duration: '1m', target: 100 },
    { duration: '1m', target: 100 },
    { duration: '30s', target: 0 },
  ],
  thresholds: {
    http_req_duration: ['p(95)<2000'],
    http_req_failed: ['rate<0.1'],
  },
};

export default function () {
  const taskId = `task-${Math.floor(Math.random() * 1000)}`;

  const createRes = http.post(`${TASK_API}/api/v1/tasks`, JSON.stringify({
    title: `Load Test Task ${taskId}`,
    description: 'Generated by k6 during chaos experiment',
  }), {
    headers: { 'Content-Type': 'application/json' },
  });

  check(createRes, {
    'create task status 201': (r) => r.status === 201,
  });

  if (createRes.status === 201) {
    tasksCreated.add(1);
    const body = JSON.parse(createRes.body);
    if (body.data_source === 'Circuit_Breaker_Fallback' || body.data_source === 'Redis_Cache') {
      fallbackRate.add(true);
    } else {
      fallbackRate.add(false);
    }
  }

  const getRes = http.get(`${TASK_API}/api/v1/tasks/${taskId}`);
  check(getRes, {
    'get task status 200': (r) => r.status === 200 || r.status === 502,
  });

  requestDuration.add(getRes.timings.duration);

  sleep(0.5);
}
