apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: "{{ .Values.backend.env.DATABASE_URL }}"
  REDIS_PASSWORD: "{{ .Values.backend.env.REDIS_PASSWORD }}"
